### PR TITLE
Add main menu navbar

### PR DESCRIPTION
**Pull request by s1f102200233**
- Implement main menu functionality in the navbar
- Add base.html describing navbar
- Include links to dashboard, profile, and group menu

### CODE REVIEW

**Review by s1f10220252 — APPROVED** [review]
base.htmlありがたいです🙏

**Comment by Mighty-Mask** [comment]
OK

**Review by Mighty-Mask — APPROVED** [review]
OK

**Review by Mighty-Mask — APPROVED** [review]

**Review by Mighty-Mask — APPROVED** [review]
OK

**Review by s1F102202099 — COMMENTED** [review]
ありがとう

**Pull request merged**
